### ISSUE TITLE
Баг с Элирекцией

### ISSUE THREAD

**Issue by laborga** [KranX/Vangers#10]
По приезду в нужный цикл в инкубатор, советник толкает вступительную речь к элирекции. Далее должна быть фраза в нижнем talkbox'е "Да, я подожду, советник", которую можно подтвердить галочкой. Вместо этого фраза появляется вверху, подтвердить ее невозможно, за ней идет фраза подтверждения участия в гонке, но элика Палец не дает. Начинал игру заново 2 раза - баг повторяется. Элирекци сейчас можно пройти только отняв элика у другого вангера.
![unnamed](https://cloud.githubusercontent.com/assets/7137079/2589439/22950c82-ba4c-11e3-8ffe-c5c0fceca6ff.jpg)

**Comment by Ltttt** [comment]
Не знаю, есть ли кто живой здесь ещё, но в версии для Mac данный баг остался. Можно с этим что-то сделать?

**Comment by stalkerg** [comment]
> Не знаю, есть ли кто живой здесь ещё, но в версии для Mac данный баг остался. Можно с этим что-то сделать?

А баг точно такой же?

**Comment by Ltttt** [comment]
Баг был точно такой же, но после переустановки игры, всё заработало. Прошу прощение за беспокойство)))

**Comment by stalkerg** [comment]
> Баг был точно такой же, но после переустановки игры, всё заработало. Прошу прощение за беспокойство)))

Вам спасибо что играете!
