### ISSUE TITLE
Surmap - get sources from Klim

### ISSUE THREAD

**Issue by cartoonka** [KranX/Vangers#104]
Нужно связаться с Климом и убедить его вытащить с машины, на которой есть компилящиеся исходники сюрмапа, весь код.

**Comment by stalkerg** [comment]
Вроде бы сделал.

**Comment by cartoonka** [comment]
в смысле уже и исходники есть? :) или пока только с Климом переговорил?

**Comment by stalkerg** [comment]
Так, у меня есть исходники. Закрываю.
