### ISSUE TITLE
Неполадки на мирах в сетевой игре

### ISSUE THREAD

**Issue by Aidoneus** [KranX/Vangers#108]
- [x] Грибы мгновенно (или крайне быстро) отрастают обратно. Когда "дым" развеивается, они уже на месте. На Некроссе доходит до смешного: если достаточно сильно налететь на гриб/группу грибов, игрок может спровоцировать многократный взрыв одного и того же гриба за крайне малый промежуток времени (довольно опасно). На Глорксе легко услышать, как без остановки воспроизводится звук лопания грибов (там они лопаются сами по себе, как и положено; просто опять проявляется баг в виде того, что это происходит крайне часто, по-видимому). Некоторые грибы перестают лопаться, если уехать от них подальше (оставить за пределами экрана), а потом вернуться. Некоторые – нет;
- [ ] Ехал по Некроссу, увидел [такой](http://imgur.com/4vplAg9l.png) баг с водой (?);
- [ ] Стоя на Некроссе на Безумном Коновале, выкинул из трюма лёгкий махотин над самим собой. В тот момент, когда он должен был попасть в мой трюм, игра мгновенно молча закрылась. Зашёл потом на Глоркс, подобрал предмет (инкарнатор неактивный) - он оказался в трюме, примерно секунду на него посмотрел и опять самозакрытие игры. В logfile.txt пишется такой текст:
```
Abbort: Connection's problems: 4  72024066  4 code:1 val:-1
Subj:
```
- [ ] Лава на Трилле очень медленно убивает игрока, как в мультиплеере оригинальной игры, а не как в одиночной/zMod'е. Хотя при этом огненные шары (и подобная активность на других мирах) в мультиплеере сейчас присутствуют, как в zMod'е, а не оригинала.

**Comment by stalkerg** [comment]
грибы поправили.

**Comment by stalkerg** [comment]
Баг  с водой это известные глюки отрисовки.

**Comment by Aidoneus** [comment]
Оставшиеся баги разнесу по другим таскам.
