### ISSUE TITLE
Баг с вращающейся камерой(и не только)

### ISSUE THREAD

**Issue by dester42** [KranX/Vangers#126]
При попытке покрутить пятаки с включенным автовращением, автомасштабированием и наклоном камеры игру выбивает. Тоже касается и любых ползающих терминаторов
Ещё забавный баг. При включенном автомасштабировании на всех машинах со скоростью 7 и выше (с учётом включенного ускорения)  камера начинает приближать, а не отдалять

**Comment by stalkerg** [comment]
Из-за того что игра очень экономно пытается общаться с памятью (на лету декомпресирует то что нужно для рендринга) то в ней всегда был "баг" с выходом за границы массива, на малых разрешениях это было крайне редкостью (всё помещалось).

**Comment by caiiiycuk** [comment]
Гарантированно воспроизводится крэш, со следюущими входными значениями:
**vmap.cpp**
```
void vrtMap::SlopTurnSkip(int Turn,int Slop,int H,int F,int cx,int cy,int xc,int yc,int XDstSize,int YDstSize)
{
	Turn = -5130;
	Slop = -210;
	H = 600;
	F = 512;
	cx = 966;
	cy = 1024;
	xc = 640;
	yc = 360;
	XDstSize = 640;
	YDstSize = 360;
	PerpSlopTurn(Turn,Slop,H,F,cx,cy,xc,yc,XDstSize,YDstSize);
}
```

HD режим, выходим в мир и нажимаем прыжок - падение
