### ISSUE TITLE
Некорректное отображение финальных текстов

### ISSUE THREAD

**Issue by Ben-zin** [KranX/Vangers#139]
![screenshot_20180313_004111](https://user-images.githubusercontent.com/34771538/37300041-93b004dc-2657-11e8-8c76-94e86aca6b2d.png)
![screenshot_20180313_004101](https://user-images.githubusercontent.com/34771538/37300042-93def0ee-2657-11e8-817b-b6e90450a144.png)

Неверная перерисовка частей текста, выходящих за фоновое изображение, при перелистывании.

**Comment by stalkerg** [comment]
Судя по всему это hd версия?

**Comment by Ben-zin** [comment]
yep

**Comment by stalkerg** [comment]
А в обчыной проверял? (master)

**Comment by Ben-zin** [comment]
В обычной норм, текст за фон не выходит.

**Comment by stalkerg** [comment]
Исправили в #464
