### ISSUE TITLE
Музыкальная тема икспло (криво нарезана?)

### ISSUE THREAD

**Issue by Ben-zin** [KranX/Vangers#145]
В конце трека икспло в игре звучит первая нота темы малых миров.

**Comment by stalkerg** [comment]
А ты сам файл (ogg) открывал? Там реально так? (сейчас не могу проверить)

**Comment by Ben-zin** [comment]
Да, файл с касяком.

**Comment by stalkerg** [comment]
Скорее всего рипали с диска и попало немного с другой дороги... это была раньше частая проблемма. Но увы ничего тут поправить не могу, за что купил за то и продаю. :)
