### ISSUE TITLE
Мехосома: Учет товаров

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#152]
Помню этот глюк с давних времен. Думаю он так и остался.
Цель мехосомы: продажа товаров. Кто первым привезет нужное число в эскейвы -тот и победит.
Но игра оказывается учитывает факт продажи любого товара в любом эскейве.

Т.е. приехав в инкубатор продаем нимбос, который был при себе. Забиваем трюм флегмой.
Выезжаем на поверхность (почему-то это важно). Возвращаемся в инкубатор, продаем флегму - и всё, она засчитывается. Вместо поездки до Подиша просто топимся в канаве и сразу респавн.

При умелом использовании может дать значительное преимущество. 
Считаю что надо фиксить, ибо не совсем справедливо учитывать за успешно привезенную флегму ту, что была продана там же где и куплена.

**Comment by stalkerg** [comment]
Думаю просто особо не заморачивались на счёт правил... не уверен только где эта логика, в сервере или на клиенте.
