### ISSUE TITLE
Полностью отсутствует звук

### ISSUE THREAD

**Issue by toby3d** [KranX/Vangers#154]
Не уверен связано ли это с последними обновлениями, но и в GOG, и в Steam версиях игры полностью отсутствует звук и музыка.
Операционка: Arch Linux 4.16.0-1-MANJARO

**Comment by stalkerg** [comment]
А что пишет в консоле? Кроме того у вас pulseaudio или alsa? Используется обычная SDL2.

**Comment by toby3d** [comment]
В консоле ничего криминального, юзаю PulseAudio

**Comment by stalkerg** [comment]
Попробуйте запустить игру из консоли руками так что бы в первую очередь использовалась системная sdl2 а не та что идёт с игрой. 
И попробуйте запустить с SDL_AUDIODRIVER=alsa path_to_vangers_bin
