### ISSUE TITLE
Слайдшоу после виксова

### ISSUE THREAD

**Issue by dester42** [KranX/Vangers#155]
Причина слайдшоу после коридора виксов-фострал является то что мехос застревает в текстуре коридора.  Точнее он застревает под миром, от сюда и сладшоу.  А так же если расплавить жёлтую поверхность с помощью танкацида то эта проблема решается, но не полностью. Пока мы находимся на коридоре слайд шоу всё ещё проиходит, но как только мы съезжаем со спирали всё становится нормально

**Comment by dester42** [comment]
UPD. Всё проходит после нескольких секунд слайдшоу

**Comment by stalkerg** [comment]
Это в steam/gog версии или с HD пачем?

**Comment by dester42** [comment]
Это стим версия с HD патчем

**Comment by stalkerg** [comment]
Я думаю это вариант вот этой баги #126

**Comment by lpenguin** [comment]
@stalkerg закрываем?

**Comment by stalkerg** [comment]
@lpenguin думаю да, вроде больше никто не жаловался.
