### ISSUE TITLE
Вылеты в стим версии

### ISSUE THREAD

**Issue by Garlic21** [KranX/Vangers#156]
Без ошибки кидает на рабочий стол,а причина вылетов достаточно интересная,пришлось 4 раза начинать сначала дабы проверить.
Первый разы вылеты начались после того как я начал катать с липурингой в трюме.Можно было хоть 5 часов играть без вылетов,но после выкапывания липуринги начинались вылеты.
Так же замечал вылеты после загрузки автосейва буквально через 2 минуты.
В крайний раз теста,увидел особенность..Вылеты начинаются после открытия глоркса..допустим мы взяли фелгму и поехали в подиш,если при этом стрелять по мехам(проверял на горбах с вектором)то вылет обеспечен(не важно как часто стрелять и сколько находиться пуль на экране).Если ехать и не стрелять то я спокойно доберусь до подиша. 
Так же вылеты случались после возвращения с других миров через 1-2 минуты.
Не знаю даже имеет ли все это связь..очевидно одно что при начале новой игры и катания по фостралу вылетов не было

**Comment by stalkerg** [comment]
Нужен сейв где можно было бы выйти и сделав минимальное колличество действий получить вылет.

**Comment by mustdieunseen** [comment]
Доброго! У меня стим-версия. Вылеты начинаются с почернения предметов в инвентаре. при попытке кликнуть в почернение - вылет. Почернение появляется после выполнения табутаска. У меня был "обстрелять 5 вангеров из других миров". после захода в эскейв предметы пропадают. в моем случае был Огород - пропал раббокс. Дождался цикла - выкопал новый. Вышел из эскейва - предметы вернулись, но войти на Глорксе никуда не могу - вылетает.
Как повторить: войти в эскейв в данном сейве. 
[save00.zip](https://github.com/KranX/Vangers/files/2341657/save00.zip)

**Comment by stalkerg** [comment]
спасибо за сейв! Попробую исправить.

**Comment by vangerellias** [comment]
Протестировал данный баг на указанном сохранении, никаких вылетов не последовало.
https://drive.google.com/file/d/1ODFg0VNFNMzx54StyZw02WR12JZChBlq/view?usp=sharing
