### ISSUE TITLE
Баг с подбиранием предметов (?) в сетевой игре

### ISSUE THREAD

**Issue by Aidoneus** [KranX/Vangers#159]
Стоя на Некроссе на Безумном Коновале, выкинул из трюма лёгкий махотин над самим собой. В тот момент, когда он должен был попасть в мой трюм, игра мгновенно молча закрылась. Зашёл потом на Глоркс, подобрал предмет (инкарнатор неактивный) - он оказался в трюме, примерно секунду на него посмотрел и опять самозакрытие игры. В logfile.txt пишется такой текст:
```
Abbort: Connection's problems: 4  72024066  4 code:1 val:-1
Subj:
```

Проверял 28 ноября 2017 года. В тот же день удалось несколько раз повторить баг, но потом на неделе воспроизводился нестабильно уже. Сейчас не знаю, есть ли он, нет ли - надо тестировать.

**Comment by gerraz** [comment]
Проверил на 7 windows-ничего подобного замечено не было, ни на Некроссе, ни на Глорксе.
https://drive.google.com/file/d/1f6S0mGvggthl5vkLE0vvd2KIEsn-foCT/view?usp=sharing
