### ISSUE TITLE
ESC нажатие в мире

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#173]
Когда находишься на поверхности и нажимаешь ESC  - открывается меню.  
Закрыть его можно только нажатием "продолжить игру"
Возможно повторное нажатие ESC тоже должно быть эквивалентно "продолжить игру"

**Comment by DiTolk** [comment]
Примерно из той же оперы в эскейве
После сохранения в ячейку остается активным окно сохранения и нужно сделать дополнительное действие: нажать на галочку. 
Типа "да-да, я сохранился, и теперь хочу продолжить игру".

Да, там есть кнопка удаления сейва слева, но предполагаю что пользуются ей исключительно редко и до нее можно добраться повторным открытием окна, если очень хочется. Но каждый раз после сохранения жмакать еще и на галочку - утомляет >_<

**Comment by Aidoneus** [comment]
Да, всё ещё присутствует и народ жалуется.

**Comment by Fenex** [comment]
Fixed by PR #257, needs to close.
