### ISSUE TITLE
Хочешь взглянуть на мир по-новому?

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#174]
При первом рейде в Инкубатор надпись с рекламой функций камеры выскакивает буквально каждые 30 секунд. Причем даже если включить все функции и поиграться ими немного - она продолжает всплывать.

**Comment by stalkerg** [comment]
Да. Надо убирать если игрок уже включал все опции.

**Comment by DiTolk** [comment]
В общем надо что-то делать. Сейчас смотрел стримершу которая включила один эффект поворота (т.е. все-таки взглянула на мир поновому) -  но ей продолжают выскакивать постоянно напоминания. Ну может не хочет человек включать-выключать все эффекты - это же не повод напоминалке его мучать. Надо подумать как это органичнее сделать

**Comment by XiadaOku** [comment]
@stalkerg @DiTolk можно закрывать
