### ISSUE TITLE
Bug during the heroism cycle on Glorx

### ISSUE THREAD

**Issue by Melodycadeance** [KranX/Vangers#175]
Logfile contains:

Abbort: uvsVanger::break_harvest : don't now where go  code:1 val:-1
Subj:

Bug leads to crash and happens all the time. I leave the escave and after some random amount of time it crashes no matter what i do.
Steam version of the game.
 # #

**Comment by Melodycadeance** [comment]
[save00.zip](https://github.com/KranX/Vangers/files/3438588/save00.zip)

Added a save file. Just take one minute on the roads of Glorx for the bug to manifest.

**Comment by stalkerg** [comment]
I know that bug, it means you play too long and some Vangers harvest all dolls for Glorx and he doesn't know what they should do. 
The dark side of the game... but I have an idea how to fix it.

**Comment by Melodycadeance** [comment]
No, that's impossible. Check the save file. I didn't even leave Glorx yet, didn't visit any other world except Glorx and Fostral. I only finished 3 or 4 tabutasks, won the race on Fostral 3 times and ranked up the first time on Glorx.
It's literally impossible for all the dolls to be harvested THIS fast. Besides, i have 50 authority and i can see that the dolls are still there, untouched.

**Comment by stalkerg** [comment]
ok, проверю еще раз. В любом случае эта ошибка с ИИ на глорксе там когда ИИ собрал все пипетки и не знает что делать дальше так как больше циклов нету. Циклы могут пропасть только если куклы собраны. 
В любом случае буду изучать на этой неделе.

**Comment by stalkerg** [comment]
Это самая последняя вресия?

**Comment by Melodycadeance** [comment]
Да, самая последняя. Обновлений в стиме на нее нет.

**Comment by ilia-nikiforov** [comment]
Same issue with the same logfile, also while going very fast and getting to Glorx asap.

**Comment by Aidoneus** [comment]
Тоже столкнулся с этой ошибкой. Могу подтвердить, что ни одна Кукла ни одного биоса не была собрана -- все на месте.

**Comment by caiiiycuk** [comment]
Just commenting `abort` helps. Maybe it's lead to undefined behavior but gameplay looks ok:
```
	if (!pg) {
//		ErrH.Abort("uvsVanger::break_harvest : don't now where go ");
		return;
	}
```
