### ISSUE TITLE
VanWar lost shots

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#177]
Версия Стим на сентябрь 2019.

При игре в ВанВар выяснилось что большинство игроков не могут друг друга убить из оружия потому что просто не видят выстрелов друг друга.

Проверяли в спокойной обстановке и порою не доходило 100% из выпущенных подряд залпов.

Таран при этом работал.

**Comment by XiadaOku** [comment]
@stalkerg @DiTolk можно закрывать
