### ISSUE TITLE
Wrong libavcodec checks

### ISSUE THREAD

**Issue by kvark** [KranX/Vangers#178]
```cpp
#if LIBAVCODEC_VERSION_MAJOR < 53 && LIBAVCODEC_VERSION_MINOR < 35
```
This would turn out to be true on versions like "60.30", which I don't think were meant to be covered?
Perhaps, the proper check would be:
```cpp
#if LIBAVCODEC_VERSION_INT < AV_VERSION_INT(53, 35, 0)
```

**Comment by stalkerg** [comment]
merged and fixed.
