### ISSUE TITLE
Не запускается английская linux версия

### ISSUE THREAD

**Issue by Voker57** [KranX/Vangers#21]
На запуск в steam нет реакции.

Запуск через консоль:

`[voker57@nbl-thinker 0] ~/.steam/steam/SteamApps/common/Vangers/bin% ./linux/vangers32
"VANGERS: One For The Road" by K-D Lab (SDL Version)
Release (ENG)
[voker57@nbl-thinker 1]`

**Comment by Vintodrimmer** [comment]
Добрый день.

Клонировал, установил по инструкции, скопировал директорию `resources`, но при запуске получаю лишь

```
➤ ../build/src/vangers
"VANGERS" by K-D Lab (SDL Version)
Release (RUS)
```

Система 64 бита, Void Linux.

**Comment by stalkerg** [comment]
@Vintodrimmer пожалуйста откройте отдельную issue. Кроме того уточните, что за ОС, что за инструкция и причём тут папка resources а не data?
