### ISSUE TITLE
Пропал цикл с пипшоу

### ISSUE THREAD

**Issue by vano55ermo** [KranX/Vangers#221]
После героизма сразу ядерная война, и после нее опять героизм, перезаходы в игру не помогли, софтлока по факту нету: можно за бибы агентом стать, но хочется буравчика покатать
Когда впервые попал на Глоркс, этот цикл был

**Comment by bugreportedman** [comment]
Если я правильно помню, то при ловле и сдаче кукол закрываются соответствующие им циклы. Так что если вы поймали одну, то это и должно быть так.

**Comment by stalkerg** [comment]
Да циклы на любом из миров не что то постоянное. 
Пока закрою. Если вдруг все куклы на месте то тогда открою опять и будем думать как к этому пришло.
