### ISSUE TITLE
В свежеустановленной игре поломанное управление

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#225]
Абсолютно нефункциональное управление, видимо из-за какой-то ошибки в интерптретации шрифтов

В итоге если новичок просто сразу стартует игру - его ждет ад и непонимание.
Сколько-нибудь приемлемое стандартное управление возвращается если нажать "ВОЗОБНОВИТЬ ВСЕ"

Но само это управление тоже достаточно кривое. Например езда на крестовине, а прыжок на Insert. 
Как вариант сделать 2-3 опции наборов управления, между которыми можно переключаться. Но это в идеале. А для начала хотя бы базовое вернуть.

**Comment by Aidoneus** [comment]
Вроде как поправили. Можно закрывать?

**Comment by XiadaOku** [comment]
@stalkerg @DiTolk можно закрывать
