### ISSUE TITLE
При создании сетевой игры глючит кириллица

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#226]
На кириллице невозможно писать ники и название игры. Так же не работает Капс-Лок

Фраза "новая игра на _server name" либо превращается в кашу либо содержит лишние символы перед именем сервера (см скрин)

![2020-06-11-21-22-28 mkv_snapshot_03 48 34_ 2020 06 12_16 58 49](https://user-images.githubusercontent.com/35186540/84500730-c90b9f80-acbd-11ea-911c-f6ba29db4f5e.jpg)

**Comment by Aidoneus** [comment]
Касательно каши в "Новая игра на...": почему-то даже на одном и том же билде под Windows наблюдается картина, описанная выше, а вот на линуксе - надпись отображается правильно ("Новая игра на feek.pw").

**Comment by bearoforange** [comment]
Но на Линуксе нельзя создать игру с кириллицей в названии, а на Win можно...

**Comment by XiadaOku** [comment]
@bearoforange насчет линукса без понятия, что там, но баг этот поправлен был. И это вообще просто очередная ишка не закрытая

**Comment by Aidoneus** [comment]
Косяк с рандомными символами в "Новая игра на ..." поправили.
На линуксе сейчас собрал мастер – игра с кириллицей в названии создаётся.
Думаю, можно закрывать и правда.

**Comment by XiadaOku** [comment]
@stalkerg @DiTolk можно закрывать
