### ISSUE TITLE
Сеть: При нажатии Enter в числовом поле откидывает в предыдущее меню

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#227]
Когда заполняешь числовые параметры внутри выбранного режима игры (число бибов, число товаров, число убийств) то чтобы изменение вступило в силу необходимо нажать Enter, однако его нажатие так же провоцирует нажатие клавиши "ОК" и тебя выкидывает в предыдущее меню. Приходится вновь заходить внутрь мода, так как обычно числовых параметров 2-3 которые надо исправить. И как правило после каждого изменения выкидывает. 
Но иногда не выкидывает.

Было бы удобно если мышкой можно было кликать по параметрам и это переводило бы поле в режим редактирования:
Кликнул по числу бибов: стер старое, ввел новое. Сразу кликаешь по числу товаров и число бибов принимается, а число товаров начинает мигать для редактирования.
Ну и энтер можно оставить, лишь бы не выкидывало в предыдущее меню.

**Comment by XiadaOku** [comment]
@stalkerg @DiTolk можно закрывать
