### ISSUE TITLE
Ошибки Чата

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#231]
Нет лимита длины сообщения по границе чата, причем когда кончается длина экрана -  буквы начинают вылезать слева. 

Обнаружен так же странный баг, который едва ли мог быть обнаружен в условиях обычной игры:
Иногда после отправки нескольких сообщений если нажать "Очистить Буфер" (экран чистится) и потом на "Выйти из Чата" (не клавишу, а в окне чата) - то игра может крашнуться.
ошибку смог повторить другой игрок. но мы не смогли добиться 100% вероятности повтора.
![Chat_Limits](https://user-images.githubusercontent.com/35186540/84564055-ce71f400-ad68-11ea-8ab7-a6bbeabc10bc.jpg)
![Chat_Limits2](https://user-images.githubusercontent.com/35186540/84564059-cfa32100-ad68-11ea-938e-43db1688bd6c.jpg)

**Comment by Aidoneus** [comment]
У меня ещё работало (игра падала), если не выходя в мир зайти в чат, ввести длинную строку (вылезающую за экран до предела), нажать "Очистить буфер" и "Текущая игра" (т.е. вернуться из чата на экран игры).

**Comment by Aidoneus** [comment]
Надо потесть – теперь вроде поправлено.

**Comment by XiadaOku** [comment]
@stalkerg @DiTolk можно закрывать
