### ISSUE TITLE
Сброс отдаления камеры после перехода через коридор

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#232]
Большинство игроков в сети ездит с максимально отдаленной камерой для получения лучшего обзора окружающего мира. 
После перехода через коридор камера возвращается в исходное, сильно приближенное положение. И чтобы отдалить её обратно - приходится вновь отзумливаться что происходит медленно (что само по себе не плохо, просто несвоевременно) и нажатия остальных кнопок становятся проблемными.

Решение: не сбрасывать значение приближения камеры после перемещения через коридор

**Comment by Aidoneus** [comment]
Может быть, это можно сделать тем же способом, что и для сохранения настроек (поворот, автоотдаление, наклон) камеры?

**Comment by DiTolk** [comment]
@Fenex  YOU ARE PURE GENIUS, SIR!
THANK YOU FOR THIS RELIEF!
