### ISSUE TITLE
 Cетевая: Пропажа мехоса другого игрока

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#237]
Такое случалось и раньше:
иногда мехос другого игрока становился невидимым, но само пространство было заполнено "телом" мехоса, его можно было таранить. Ник при этом видно, при езде оставались следы от шины и пыль из под колес. Иногда это могло длиться долго, иногда  несколько секунд, потом появлялся.

Зачастую игроку, у которого пропал мехос, кажется что у других тоже пропадают мехосы.

На скрине пропажа произошла у Бензина, но через несколько секунд он появился. При этом он говорил что у него пропадают другие игроки. А во время Ван-Вара он не видел выстрелы противников вообще.
P.S. Haedes походу тоже исчез на этом скрине)

![Invisible_Error](https://user-images.githubusercontent.com/35186540/84598383-f483bb00-ae72-11ea-9060-ff24b81c8f8d.jpg)

**Comment by Ben-zin** [comment]
Уточняю: мехосы пропадали периодически, не видел вообще ни чьих выстрелов ни в одном из модов, мои тоже никто не видел, невозможно было кого-то убить пушкой.
Клиент linux64.
Так же по опросу в чате у кого-то тоже на лине была такая же проблема.

**Comment by DiTolk** [comment]
Вот бонусом момент, когда даже мехос игрока у меня исчез и почти все остальные мехосы (в конце видео появляется один видимый)
![All_INvisible](https://user-images.githubusercontent.com/35186540/85202564-dbb25400-b30f-11ea-850f-2b4a203014cd.jpg)
[All_Invisible_Error.zip](https://github.com/KranX/Vangers/files/4807916/All_Invisible_Error.zip)

**Comment by DiTolk** [comment]
Новые данные: игроки на линуксе не видят выстрелы игроков с виндоуса (и наоборот) а также линуксоиды не видят выстрелы других линуксоидов. 100% пропажи пакетов. Против них работает только таран корректно вроде.
Т.е. если играешь на линуксе тебе кажется что никто вокруг не стреляет. а твои выстрелы никого не ранят так как не доходят до них

**Comment by Aidoneus** [comment]
[Демонстрация на видео](https://www.youtube.com/watch?v=P3KKdHnPALk). Как-то совсем уж жёстко пропадает и моргает

**Comment by Fenex** [comment]
needs to be closed

**Comment by XiadaOku** [comment]
@stalkerg @DiTolk можно закрывать
