### ISSUE TITLE
Сетевая игра: ограничение времени существования Ван-Вара

### ISSUE THREAD

**Issue by Aidoneus** [KranX/Vangers#251]
При создании игры типа Ван-Вар есть настройка, позволяющая выставить максимальное время существования игры в минутах, по прошествии которого игра должна заканчиваться, как если бы кто-то набрал максимальное количество фрагов, и матч завершился бы для всех.

Проблема в том, что сервер не присылает реальное время создания игры, или срок существования игры - ничего такого.

И время, указанное в настройке, сравнивается вместо этого для каждого клиента отдельно с моментом его, клиента, захода в игру. То есть если я зашёл в матч через 20 минут после остальных - то по таймлимиту у всех игра закончится с разницей в несколько секунд-минут (смотря кто когда зашёл), а я буду ещё 20 минут кататься по миру, прежде чем то же самое у меня случится. Явно неправильное поведение.

**Comment by bearoforange** [comment]
Вроде как теперь сервера и клиенты синхронизированны, говорит **Xiada**. Баг исправлен.
