### ISSUE TITLE
Сингл: Мехос застревает в люке эскейва при  выходе

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#265]
Начало игры: при первом выходе из эскейва мехос застревает в люке (верхний выход Подиша), который не открывается.
Если зайти обратно и выйти вновь, то в случае если выход опять из верхнего - это повторится.

Возможно и в дальнейшем продолжении игры это происходит
[Escave_Stuck_Exit.zip](https://github.com/KranX/Vangers/files/4906841/Escave_Stuck_Exit.zip)

**Comment by Fenex** [comment]
possible duplicate #143
