### ISSUE TITLE
Abbort: iObject not found... code:1 val:-1

### ISSUE THREAD

**Issue by ZeeWanderer** [KranX/Vangers#266]
Env: Windows 10 x64, GOG game version

I updated game data by copying folders from [data](https://github.com/KranX/Vangers/tree/master/data) to the root game directory.

After I launch the game I get 

```
Abbort: iObject not found... code:1 val:-1
Subj:
```
I traced it to `EscaveTrig` variable that is added in dc57a14cd1652ebdca1f60895a21a9276ec9f589. Variable is in the files that are copied to the game root folder but the variable is not found. Am i doing something wrong?

**Comment by Aidoneus** [comment]
Looks like you have to compile binary script files (containing new interface features) first.
1. Build the game with BINARY_SCRIPT flag set to OFF;
2. Launch the game once - it'll generate needed files (.scb files in data/resource/iscreen and data/resource/actint);
3. Now you can build the game without aforementioned flag and play it as usual.

**Comment by ZeeWanderer** [comment]
Is adding this to CI an option? Or maybe providing compiled binary scripts via a link in readme? Or at least adding this to doc.
