### ISSUE TITLE
Сеть: Пропажа товаров в мехосоме

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#282]
Если в мехосоме выйти из эскейва не купив товар, или выкупив не весь и  потом зайти в эскейв вновь - возможности купить товар не будет.  Он появится только тогда, когда игрок посетит противоположный эскейв.

Долгое время это воспринималось нами как багофича "на внимательность", но все же это противоречит логике и здравому смыслу. Поэтому невыкупленный товар должен оставаться в эскейве, а после посещения противоположного эскейва восполняться до максимума, указанного в параметре Мехосомы "Доступно за раз"

**Comment by ESandu** [comment]
Господи, да! Наконец-то ты признал это багом!
