### ISSUE TITLE
Надоедливый совет на старте игры о Камере

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#288]
Смотрел стрим и заметил что начавшему игру Вангеру буквально каждую минуту вылезает сообщение "Хочешь взглянуть на мир по-новому? Открой настройки Камеры" и   он все равно его игнорил будто не замечал. Но то, с какой частотой это выводилось- кошмар. Я помню что вроде если игрок откроет настройки и хоть что-то изменит - оно исчезнет.  Но считаю что лучше поставить дополнительное условие по длительности и частоте показа, что-то вроде
показывать его раз в 10 минут 4 раза за первые 40 минут игры. если так и не откроет Камеру - перестать показывать.

**Comment by Fenex** [comment]
duplicate #174

**Comment by XiadaOku** [comment]
@stalkerg @DiTolk можно закрывать
