### ISSUE TITLE
Shift - T (CTRL - T)  Fix

### ISSUE THREAD

**Issue by DiTolk** [KranX/Vangers#292]
Сочетание клавиш Shift-T (и как выяснилось такой же эффект от CTRL-T) вызывает разблокировку FPS и ускорение игры, а повторное нажатие - понижение до 2-3FPS. Причем возвращение в нормальное состояние возможно только при перезапуске приложения (прервать игру и зайти снова-  не спасает)

Во время сетевой игры некоторые случайно нажимали это сочетание. Также в Стим Комьюнити был пост от игрока, у которого ускорение на Шифт (что обычно) и прыжок на T   - и  у него игра каждый раз начинала сходить с ума.

Каков функционал этого инструмента? 

Как вариант сделать его вызов чуть более защищенным от случайного нажатия, например CTRL-Shift-T

**Comment by Aidoneus** [comment]
Или вообще для мастер-ветки закомментировать его, как функцию для "постеров". Кому надо – раскомментируют для тестов или чего бы то ни было ещё.
