### ISSUE TITLE
Вылет в ходе Ядерной войны

### ISSUE THREAD

**Issue by BuHToPe3** [KranX/Vangers#293]
ОС Windows 7 x64, игра запускается через Steam. Бета-версия (turbospiralnab).

Вылет на Глорксе в ходе Ядерной войны. 
Игра молча закрывается.
Повторилось два раза.
Один раз я просто ехал по своим делам, словил вылет, перезапустился и продолжил играть.
Второй раз я сам участвовал в Ядерной войне. Есть предположение, что в момент вылета бот пытался взять ядро, которое было в труднодоступном месте на карте.

Лог-файл (содержимое одинаково после обоих вылетов):
[logfile.txt](https://github.com/KranX/Vangers/files/5012515/logfile.txt)

**Comment by BuHToPe3** [comment]
Поймал ошибку в третий раз. 
Прикрепляю сейв на котором ошибка воспроизводится (пробовал загружать его три раза). 
При выходе из эскейва игра падает в течение минуты.
[KRW_crash_save.zip](https://github.com/KranX/Vangers/files/5012625/KRW_crash_save.zip)

**Comment by DiTolk** [comment]
Отлично! Спасибо огромное за сейв

**Comment by BuHToPe3** [comment]
> Будет возможность- проверьте с обычной версии стима этот же сейв. По идее должно повториться, ибо бета сейчас менюшки управления меняет только

Проверил на обычной Steam-версии, на этом сейве. Игра закрылась через 5-10 секунд после выхода из эскейва.

**Comment by Fenex** [comment]
На linux'е не смог воспроизвести вылет на этом сейве (d4a22555)

**Comment by Stopkot** [comment]
У меня эта ошибка тоже случилась, думал сейв пропал, но можно отсидеться на эскейве

**Comment by XiadaOku** [comment]
@stalkerg думаю можно закрывать
