### ISSUE TITLE
На поверхности играет музыка главного меню

### ISSUE THREAD

**Issue by 2manovG** [KranX/Vangers#294]
Если зайти в эскейв, в менюшке паузы выключить музыку, выйти на поверхность и включить музыку, то вместо темы мира заиграет тема главного меню

**Comment by DiTolk** [comment]
Проверил и в начале игры и с сейва на глорксе - все так

**Comment by stalkerg** [comment]
Проверьте в бете, если этого бага больше нет то закроем.

**Comment by vangerellias** [comment]
Проверил, баг неактуален. https://drive.google.com/file/d/1-N9sgWJW8HMpmZMMXFI6-ua26lgBeyYa/view?usp=sharing
