### ISSUE TITLE
Баг с размножением Бутсектора

### ISSUE THREAD

**Issue by Tugrik88** [KranX/Vangers#330]
При использовании Бутсектора с перемещением в Мехос, возможно его быстро выкинуть и в итоге получается копия Бутсектора.

![image](https://user-images.githubusercontent.com/70979985/92527211-544df000-f22f-11ea-9353-99ddb29d8d34.png)
![image](https://user-images.githubusercontent.com/70979985/92527831-5b293280-f230-11ea-9075-bcbe4310c729.png)
![image](https://user-images.githubusercontent.com/70979985/92527758-3634bf80-f230-11ea-84b9-6d5f643d2062.png)
![image](https://user-images.githubusercontent.com/70979985/92527893-7ac05b00-f230-11ea-82ec-750330cf87ac.png)

Сэйв с несколькими Бутсекторами: 
[save07.zip](https://github.com/KranX/Vangers/files/5226624/save07.zip)

**Comment by DiTolk** [comment]
Крутота, спасибо!
Мне кажется самое простейшее решение: блокировать вызов трюма после активации Бут-сектора
Вуаля!

**Comment by Tugrik88** [comment]
Прикрепляю сэйв.
[save07.zip](https://github.com/KranX/Vangers/files/5226617/save07.zip)

**Comment by XiadaOku** [comment]
@stalkerg можно закрывать
