### ISSUE TITLE
Update credits page for new contributers

### ISSUE THREAD

**Issue by stalkerg** [KranX/Vangers#332]
The current credits page (Russian) have no any notice about the steam release and new contributors.

**Comment by stalkerg** [comment]
Думаю тут будут все русскоязычные так что напишу мысли на русском. 
Мы должны сделать отдельную страницу с теми кто делал выпуск в Steam + новые github контрибьютеры.

**Comment by Aidoneus** [comment]
В каком формате/по какому образцу их там указывать? "Имя никнейм Фамилия, роль"?
