### ISSUE TITLE
В iscreen/scripts/tutorial.inc надписи на немецком

### ISSUE THREAD

**Issue by DileSoft** [KranX/Vangers#335]
Вот видео как они были на русском:

[2020-09-11_22-07-00.zip](https://github.com/KranX/Vangers/files/5212293/2020-09-11_22-07-00.zip)

**Comment by DileSoft** [comment]
Правильный файл от Xiada:
[tutorial.zip](https://github.com/KranX/Vangers/files/5212332/tutorial.zip)

**Comment by XiadaOku** [comment]
@stalkerg @DileSoft можно закрывать
