### ISSUE TITLE
Center pause menu

### ISSUE THREAD

**Issue by lpenguin** [KranX/Vangers#349]
Move in-game pause menu to the visible center, with taking into account current screen resolution

**Comment by lpenguin** [comment]
This actually quite a task at the first glance - Pause menu is a part of another GUI system with difference resource language parser.. So either I need to add another `anchor_center_x`  keyword and add layout functions, or look for quick hacks in the code for recalculating Pause Menu position as always centered

**Comment by stalkerg** [comment]
fixed in #464
