### ISSUE TITLE
Неправильная обработка кнопок при входе в эскейв

### ISSUE THREAD

**Issue by Aidoneus** [KranX/Vangers#362]
Кнопка "вправо" перемещает в магазин. Это работает. Но!

Если игрок заходит в эскейв, и по каким-то причинам его не должен пускать в магазин советник (привёз нимбос в Подиш, заехал в Лампассы без раббокса, привёз Спумия/Механического Мессию и т.п.), то если удерживать при входе в эскейв (иногда даже просто нажать достаточно) кнопку "вправо" – игрока успеет перекинуть в магазин. Что есть неправильное поведение. После этого если, закончив свои дела, переключиться на советника обратно, то второй раз в магазин уже не попадёшь, конечно; но обычно и не надо.

**Comment by vangerellias** [comment]
Проверил данный баг на свежей версии игры. Мне кажется, он уже неактуален.
https://drive.google.com/file/d/1CpnquSw1vyGijJmAOiDU5mdgUzxl3DCV/view?usp=sharing
