### ISSUE TITLE
Вопрос - почему грибы на Фострале не взрываются при таране?

### ISSUE THREAD

**Issue by NtsDK** [KranX/Vangers#377]
Возможно это задумка по геймдизайну, но это известная проблема, что машины с низко стоящим оружием легко очищают дорогу от грибов перед собой, а с высокостоящим оружием остается только прыгать.
Причем вроде на Глорксе есть штуки, которые взрываются при таране.
Может имеет смысл подрывать грибы тараном на Фострале?

**Comment by Aidoneus** [comment]
Не думаю. Именно что по геймдизайну задумки разные. На Фострале грибы взрываются только выстрелом, на Некроссе – от прикосновения и выстрела, а на Глорксе они взрываются только сами по себе.

**Comment by DiTolk** [comment]
Геймдизайн

**Comment by stalkerg** [comment]
Это очевидная уровняловка для крупных машин которым так тяжеле рулить. Чисто для баланса.
