### ISSUE TITLE
Спрайт описания функций/слотов может залогать и остаться (в новой бете)

### ISSUE THREAD

**Issue by alibabaskryagin** [KranX/Vangers#378]

**Comment by alibabaskryagin** [comment]
![image](https://user-images.githubusercontent.com/72692059/95677542-6638ff00-0bf0-11eb-810a-4f810343ff48.png)

**Comment by alibabaskryagin** [comment]
![image](https://user-images.githubusercontent.com/72692059/95677600-c62fa580-0bf0-11eb-8196-e20d293b4f1d.png)

**Comment by alibabaskryagin** [comment]
![image](https://user-images.githubusercontent.com/72692059/95677635-f8d99e00-0bf0-11eb-9bbe-f7b1c74a9b12.png)

**Comment by DiTolk** [comment]
На всякий случай пиши операционную систему тоже

**Comment by Aidoneus** [comment]
Скорее всего везде проявляется (у меня на дебиане тоже такое поведение)... но да, лучше написать.

**Comment by alibabaskryagin** [comment]
Наблюдается на 10 windows (домашней)
