### ISSUE TITLE
Баги при использовании HD расширения

### ISSUE THREAD

**Issue by Lamihuza** [KranX/Vangers#388]
1) При использовании способности Начертателя "Оградка", полупрозрачная стенка, которая изображает эту самую оградку, все время находится в центре экрана, в то время как мехос находится всегда левее, и входит в эту оградку лишь частично (не могу предоставить скриншот, т.к. на нем стенку вообще не видно ¯\_(ツ)_/¯)
2) На Глорксе на миникарте появились разрывы, через которые видно игровой мир
3) Мехос недалеко от Огорода может растянуть
![20201026103608_1](https://user-images.githubusercontent.com/73455705/97132903-d3b16780-177a-11eb-9c23-7c2617f235c1.jpg)
![20201026105307_1](https://user-images.githubusercontent.com/73455705/97132914-d7dd8500-177a-11eb-8c67-1621adbee35e.jpg)

**Comment by lpenguin** [comment]
@Lamihuza Спасибо больше, что потестил! Если будут еще находки, разбивай их на отдельные issue пожалуйста.

**Comment by lpenguin** [comment]
Я разбил ишку на три, так что эту закрываю
