### ISSUE TITLE
Баг оградки

### ISSUE THREAD

**Issue by lpenguin** [KranX/Vangers#389]
Бага из #388 
> При использовании способности Начертателя "Оградка", полупрозрачная стенка, которая изображает эту самую оградку, все время находится в центре экрана, в то время как мехос находится всегда левее, и входит в эту оградку лишь частично (не могу предоставить скриншот, т.к. на нем стенку вообще не видно ¯_(ツ)_/¯)

**Comment by stalkerg** [comment]
требуется перепроверка но вроде пофикшено
