### ISSUE TITLE
Искажение модели мехоса

### ISSUE THREAD

**Issue by lpenguin** [KranX/Vangers#391]
Из #388 
> Мехос недалеко от Огорода может растянуть
![9356E510-E4C5-44B4-AB3E-0E3D8611BB7A](https://user-images.githubusercontent.com/564449/97203244-9aeab000-17c5-11eb-8577-da7fcadb5150.jpeg)

**Comment by caiiiycuk** [comment]
@DileSoft назначь на меня пожалуйста

**Comment by caiiiycuk** [comment]
Воспроизводятся на origin/master

**Comment by caiiiycuk** [comment]
@DileSoft можно закрыть это дубликат

**Comment by caiiiycuk** [comment]
Кстате эта штука не починена, а заворкэрануджена зумом. Так для истории...
