### ISSUE TITLE
Баг эффекта от использовании способностей Механической Мессии (HD версия)

### ISSUE THREAD

**Issue by Lamihuza** [KranX/Vangers#394]
Эффект отображается в центре экрана, в то время как мехос находится чуть левее.
P.S.: Во время проверки другого бага заметил, что при приближении камеры мехос отображается не ровно в центре, а, опять же, левее. Я предполагаю, что если сместить камеру влево, то можно "пофиксить" этот баг, а так же баг отображением оградки: [https://github.com/KranX/Vangers/issues/389](url)
![5](https://user-images.githubusercontent.com/73455705/97296544-650c0100-1883-11eb-94cf-d6d346d9fb24.jpg)
![20201027180803_1](https://user-images.githubusercontent.com/73455705/97296562-6ccba580-1883-11eb-851f-7e15cee33764.jpg)

**Comment by stalkerg** [comment]
fixed in #464 если вдруг не поправлено - переоткроем так что нужна ещё проверка
