### ISSUE TITLE
Баг с инвентарем (HD версия)

### ISSUE THREAD

**Issue by Lamihuza** [KranX/Vangers#395]
Во время наведения, или взятии какого-то предмета, текст с информацией, который отображается в нижнем окошке, либо не появляется, либо появляется на долю секунды. 
Так же сам инвентарь резко обрывается, что тоже выглядело как баг, но скорее всего так и должно быть, но если так, то все равно решение разделить выглядит необоснованный и нижнее окно чувствуется инородным, я бы оставил инвентарь как в обычной версии.
![1](https://user-images.githubusercontent.com/73455705/97297476-b10b7580-1884-11eb-9ce8-5b6f0bce817a.jpg)

**Comment by lpenguin** [comment]
@Lamihuza Привет! Спасибо еще раз за столько находок

> Так же сам инвентарь резко обрывается, что тоже выглядело как баг, но скорее всего так и должно быть, но если так, то все равно решение разделить выглядит необоснованный и нижнее окно чувствуется инородным, я бы оставил инвентарь как в обычной версии.
Инвентарь пришлось разрезать, да. Чтобы сделать сплошное изображение нужен художник, причем с руками, т.к. стиль у Вангеров сложный, сгенерированный в специальном редакторе. Так что решили пока пойти на компромисс.

**Comment by Lamihuza** [comment]
> Инвентарь пришлось разрезать, да. Чтобы сделать сплошное изображение нужен художник, причем с руками, т.к. стиль у Вангеров сложный, сгенерированный в специальном редакторе. Так что решили пока пойти на компромисс.

Я, кстати, художник, и могу дорисовать инвентарь. Можем где-нибудь списаться, чтобы мне описали, что за редактор и нюансы, если таковые есть.

**Comment by stalkerg** [comment]
@Lamihuza давайте мы с вами поговорим

**Comment by caiiiycuk** [comment]
Сломалось тут:
```
commit 0b4fb6743ab8be4ec104c51f96e6fcdbf5bac789 (HEAD, refs/bisect/bad)
Author: Nikita Prianichnikov <lpenguin@yandex.ru>
Date:   Wed Aug 26 20:26:59 2020 +0300

    Fixed item drop mechanics
```
