### ISSUE TITLE
Баг с отображением текста в концовках (HD версия)

### ISSUE THREAD

**Issue by Lamihuza** [KranX/Vangers#396]
В концовках текст отображается смещенным
![20201101234339_1](https://user-images.githubusercontent.com/73455705/97808981-a98d0780-1c9c-11eb-89f5-dbdffd185efe.jpg)
![20201101234529_1](https://user-images.githubusercontent.com/73455705/97808985-adb92500-1c9c-11eb-8a46-2b02797a7ec4.jpg)

**Comment by stalkerg** [comment]
fixed in #464

**Comment by lpenguin** [comment]
Воспроизводится в текущей версии
