### ISSUE TITLE
client/server can't finish handshake on ubuntu 20.04

### ISSUE THREAD

**Issue by caiiiycuk** [KranX/Vangers#410]
In my case client/server does not work. I found that problem is in this code parts:
xsocket.cpp:187-189:
xsocket.cpp:211-213:
```
		if (!SDLNet_SocketReady(tcpSock)) {
			return 0;
		}
```

In my case on handshake stage `SDLNet_SocketReady returns 0`, but there is no any error on socket level. After commenting this code, everything works.

It will be good if someone check on other *nix system if the issue exists.

**Comment by bearoforange** [comment]
I am running Vangers on Ubuntu 20.3 LTS, and everything is working. I checked this file and looks like it doesn't work for me _with_ this code.

**Comment by caiiiycuk** [comment]
Fixed
