### ISSUE TITLE
Полноэкранный режим в HD

### ISSUE THREAD

**Issue by XiadaOku** [KranX/Vangers#467]
Если отключить полноэкранный режим в HD, но при этом в разрешении будет 1280*720 окно будет всё равно 800*600, а картинка 1280*720 ужмется в это окно. При этом если поменять разрешение на 800*600 и обратно всё станет нормально, чего собственно и стоило ожидать. Видимо при изменении параметра полноэкранного режима он не учитывает разрешение, ну или что-то подобное. В самой функции установки этого режима из lib задается принудительно 800*600, хотя после использования этой функции в src всё равно используется функция установки разрешения, так что не совсем понятно, что там вообще происходит.

**Comment by stalkerg** [comment]
Спасибо!
