### ISSUE TITLE
HD: Segfault (при входе в эскейв)

### ISSUE THREAD

**Issue by Fenex** [KranX/Vangers#471]
`src/units/items.cpp::aciGetScreenItem()`

Вылетает вот здесь (ссылка на последний коммит, который затрагивает проблемную строчку): https://github.com/KranX/Vangers/commit/0b4fb6743ab8be4ec104c51f96e6fcdbf5bac789#diff-9eeebcae6f5f602df555ff200bfa50cbf4e7112df21c2bbcfde68896195a3de9R1994

![photo5422863413903733230](https://user-images.githubusercontent.com/3790195/113480973-41e41e00-94c1-11eb-9183-184ee9358800.jpg)

**Comment by Fenex** [comment]
С такими изменениями падения прекращаются, и ничего другого (вроде бы) не ломается. Но выглядит как костыль.
Считаю надо внимательнее изучать что делает ломающий коммит 0b4fb6743ab .

```diff
diff --git a/src/units/items.cpp b/src/units/items.cpp
index c0c9b6f..468b20c 100644
--- a/src/units/items.cpp
+++ b/src/units/items.cpp
@@ -1991,7 +1991,13 @@ int aciGetScreenItem(int x,int y)
        mp = NULL;
        rz = -1;
        S2G(x,y,tx,ty);
-       GeneralMousePoint = Vector(getDistX(tx, ActD.Active->R_curr.x), getDistY(ty, ActD.Active->R_curr.y), 0);
+       ^M
+       if (ActD.Active) {^M
+               GeneralMousePoint = Vector(getDistX(tx, ActD.Active->R_curr.x), getDistY(ty, ActD.Active->R_curr.y), 0);^M
+       } else {^M
+               // printf("an exception was been here, x=%d, y=%d, ViewX=%d, ViewY=%d", x, y, ViewX, ViewY);^M
+               GeneralMousePoint = Vector(getDistX(tx, ViewX), getDistY(ty, ViewY), 0);^M
+       }^M

        p = (BaseObject*)(ItemD.Tail);
        while(p){
```

**Comment by Aidoneus** [comment]
Почему костыль-то? В эскейвах `ActD.Active` всегда отсутствует, поэтому проверка правильная.
