### ISSUE TITLE
Ветка beta: невозможность сделать скриншот

### ISSUE THREAD

**Issue by Aidoneus** [KranX/Vangers#489]
При нажатии клавиши снятия скриншота, установленной в настройках игры, игра мгновенно закрывается. В консоли сообщения следующие (захватил кусок с момента выхода на поверхность мира):
```
vrtMap::analyzeINI thechain/fostral/world.ini
Compressed format detected...
Start load decomp trees
Strange deltas clockDelta:7 Timer:1
ScreenShot name:Vangers0000.bmp
munmap_chunk(): invalid pointer
Aborted (core dumped)
```
При этом в папке с игрой создаётся файл Vangers0000.bmp, но размером в 0 байт.

Происходит при любом выбранном разрешении в настройках, когда включён полноэкранный режим. Когда включён оконный режим – скриншоты создаются нормально и описанной выше проблемы не происходит.

**Comment by stalkerg** [comment]
Исправил, в том числе исправил наименования файлов скриншотов.
