### ISSUE TITLE
Ветка beta: неправильное расположение подсказок на экране

### ISSUE THREAD

**Issue by Aidoneus** [KranX/Vangers#490]
В разрешении 800x600 подсказки сильно сдвинуты вбок как при открытом, так и при закрытом трюме.
В разрешении 1280x720 подсказки сдивнуты вбок при открытом трюме.
При достаточно длинных подсказках (примерно половина или больше) это затрудняет их чтение.
![Screenshot_2021-09-05_20-40-38](https://user-images.githubusercontent.com/7126889/132135034-5a81785a-2e19-4a29-b173-ef292e57e4be.png)
![Screenshot_2021-09-05_20-41-59](https://user-images.githubusercontent.com/7126889/132135043-2341d0f0-4800-4f40-804a-6332f38552d9.png)
![Screenshot_2021-09-05_20-44-09](https://user-images.githubusercontent.com/7126889/132135050-c7f2fd9b-ad46-44ab-96ef-cd919671aeb3.png)

**Comment by caiiiycuk** [comment]
Fixed in PR #493

**Comment by caiiiycuk** [comment]
@lpenguin можно закрыть если что
