### ISSUE TITLE
Ветка beta: артефакты в графике открытого трюма при разрешении 1280x720

### ISSUE THREAD

**Issue by Aidoneus** [KranX/Vangers#491]
![Screenshot_2021-09-05_20-44-09](https://user-images.githubusercontent.com/7126889/132135102-8e37b7a8-f010-403d-a685-422ff980c94d.png)
![Screenshot_2021-09-05_20-43-05](https://user-images.githubusercontent.com/7126889/132135138-561cd105-2a18-4d5d-9e2c-b795f86518b9.png)

В нижней части трюма видны красные и жёлтые элементы. Они светятся/мигают, выглядит как графический артефакт. Скорее всего, проблема в неправильных цветах при рисовании/конвертации графики трюма.

Кроме того, когда происходит открытие трюма, у интерфейсной рамки в правой верхней части экрана появляется длинная торчащая "коряга", которой нет, когда интерфейс закрыт. Она может перекрывать тексты подсказок, хотя и не сильно.

**Comment by caiiiycuk** [comment]
Ждем новый трюм без мигания и коряги
