### ISSUE TITLE
Simple GamePad support

### ISSUE THREAD

**Issue by stalkerg** [KranX/Vangers#5]
Add support GamePad.

**Comment by chaatra** [comment]
Подскажите, пожалуйста.
Была ли поддержка аналогового руля или триггеров в старых Вангерах?
В русском руководстве пользователя, есть пункт меню "Параметры джойстика" - "Руль".

**Comment by multimeric** [comment]
Out of interest, did this feature get incorporated into the Steam release, or would I have to compile it myself to get this feature?
