### ISSUE TITLE
Обновить экраны между мирами HD версия

### ISSUE THREAD

**Issue by caiiiycuk** [KranX/Vangers#504]
[gotovo.zip](https://github.com/KranX/Vangers/files/7242602/gotovo.zip)
В архиве содержаться изображения для экранов перехода между мирами 1280x720.

Скачать конверет https://github.com/lpenguin/vangers-utils-qt/releases
Преобразовать с помощью конвертера файлы в формат svs.
Полученными файлами заменить файлы из папки `/resource/video/svs`, паттерн файлов 0*.svs

Все файлы начинающиемя с 0 это файлы для версии 640x400 они не используются, если их заменить файлами 1280x720 тогда HD версия их автоматически подхватит.

**Comment by stalkerg** [comment]
@Aidoneus для тебя
