### ISSUE TITLE
Падение fps в 3d

### ISSUE THREAD

**Issue by DileSoft** [KranX/Vangers#534]
Если какое-то время ездить по миру, или поставить игру на паузу и вернуться, fps падает до 30. При этом если свернуть игру и восстановить, они могут восстановиться до 60. Если стоять на месте или крутиться вокруг себя, fps не падает, если какое-то время ехать - падает.

**Comment by lpenguin** [comment]
Воспроизводится на Windows 10/ANGLE. @DileSoft у тебя нет возможности проверить на Linux?

**Comment by DileSoft** [comment]
Сейчас нет.

**Comment by caiiiycuk** [comment]
Кстате в вебе тоже есть странность, если перейти на соседнию вкладку, побыть там некоторое время, а затем вернутся в игру. Она будет люто тормазить и как бы прокручивать то что ты пропустил какое-то время, после этого вернется в норму. Как будто какой-то буфер заполняется а потом флушится.

**Comment by caiiiycuk** [comment]
Я более предметно посмотрю на это когда баг с мерцанием поправлю...

**Comment by DileSoft** [comment]
> Кстате в вебе тоже есть странность, если перейти на соседнию вкладку, побыть там некоторое время, а затем вернутся в игру. Она будет люто тормазить и как бы прокручивать то что ты пропустил какое-то время, после этого вернется в норму. Как будто какой-то буфер заполняется а потом флушится.

А это только в 3d так, или в вебе вообще?

**Comment by caiiiycuk** [comment]
Похоже в случае с браузером при переключении вкладки позиция мехоса прагает как шальная поэтому такие тормаза, и ещё вот такой эффект бывает
![изображение](https://user-images.githubusercontent.com/1727152/151399739-ac4bc446-b5db-469c-8425-df818d237609.png)

**Comment by lpenguin** [comment]
@caiiiycuk проявляется ли у тебя бага в последней версии?

**Comment by caiiiycuk** [comment]
Неа можно закрывать. Я пофиксил (были внтренние пробелмы барузерки) с этой веткой не связанные
