### ISSUE TITLE
render-ng: memory access out of bounds

### ISSUE THREAD

**Issue by caiiiycuk** [KranX/Vangers#536]
Если переключаться между вкладками экран дрыгается и падает иногда
![изображение](https://user-images.githubusercontent.com/1727152/151400011-823e1b90-125c-48e0-b0d3-e94083c214ae.png)

**Comment by lpenguin** [comment]
Это не связано с тем "прыганьем" Мехоса в соседнем Issue? https://github.com/KranX/Vangers/issues/534#issuecomment-1023401517

**Comment by caiiiycuk** [comment]
Думаю связанно

Вс, 30 янв. 2022 г. в 13:12, Nikita Prianichnikov ***@***.***
