### ISSUE TITLE
Перепутанные каналы цветов в видео

### ISSUE THREAD

**Issue by lpenguin** [KranX/Vangers#539]
Мехосы в магазине имеют синеватый оттенок. 

Скорее всего связано с тем, что формат видео не RGBA, а Compositor поддержтвает пока только его. 

![IMG_20220130_090842_745](https://user-images.githubusercontent.com/564449/151688811-6e918a51-5ac1-4331-a235-66eed73d9622.jpg)

**Comment by lpenguin** [comment]
Да, на little-endian CPU формат видео будет BRGA: https://ffmpeg.org/doxygen/3.3/pixfmt_8h.html#a9a8e335cf3be472042bc9f0cf80cd4c5

Увы, с поддержкой BGRA в GLES2/WebGL2 не все так просто: https://www.g-truc.net/post-0734.html

Интересно как с этим работает SDL2

**Comment by caiiiycuk** [comment]
Так просто поменять же биты местами? Я в веб версии так сделал

**Comment by lpenguin** [comment]
@caiiiycuk можешь показать где менял?

**Comment by caiiiycuk** [comment]
К сожалению не могу, там просто другой код для видео

**Comment by lpenguin** [comment]
@caiiiycuk я вот так поправил, у тебя чтото похожее?
https://github.com/KranX/Vangers/pull/545

**Comment by caiiiycuk** [comment]
@lpenguin да именно так

**Comment by lpenguin** [comment]
Поправлено в https://github.com/KranX/Vangers/pull/545
