### ISSUE TITLE
Кастомное разрешение для 3d / HD версии

### ISSUE THREAD

**Issue by John888Tomson** [KranX/Vangers#548]
Добавить в настройки пункт с вписыванием кастомного разрешения. 

Как оно было в старой ветке 3д (19 года), где разрешение прописывалось через команду при запуске

**Comment by lpenguin** [comment]
@stalkerg можно добавить опции, которые при старте переопределят настройки разрешения из меню, если они переданы в командную строку.

**Comment by caiiiycuk** [comment]
https://github.com/KranX/Vangers/pull/564

Я думаю это самое удачное решение проблемы разрешения

**Comment by lpenguin** [comment]
@caiiiycuk да, отлично!

**Comment by lpenguin** [comment]
Закрываю, т.к. добавили ресайз окна в #564
