### ISSUE TITLE
Segmentation Fault при запуске

### ISSUE THREAD

**Issue by burunduk3** [KranX/Vangers#568]
На строке: https://github.com/KranX/Vangers/blob/cbf830ad381257d535fb55684507ce460e5f0360/src/iscreen/iextern.cpp#L782

Выглядит как будто `objPtr` не инициализирован. Возможно, имелось в виду записать туда `new iTriggerObject();`, как в соседних опциях?

**Comment by caiiiycuk** [comment]
Почему? Дум все впорядке

**Comment by burunduk3** [comment]
Потому что когда я словил этот креш, я добавил пару строчек отладочного вывода, пересобрал и `iScrOpt[iFULLSCREEN]->objPtr` оказалось `nullptr`.

Но, возможно, предполагается, что он где-то раньше инициализируется, а у меня этого почему-то не случилось. Могу позже попробовать разобраться.

**Comment by caiiiycuk** [comment]
В любом случае присвоение функци. Не может дать nullptr. Т.е. да не правильный порядок инициализации… но почему

**Comment by burunduk3** [comment]
Да понятно, как может. Если `objPtr` — `null`, то в попытка записать что-то в `objPtr->callback` вполне справедливо приводит к падению.

Как там оно инициализируется я не смотрел пока что. Но, если это может влиять, у меня данные (ресурсы всякие) старые, ещё чуть ли не с оригинального диска из 1999-го.

**Comment by caiiiycuk** [comment]
Они 100% работать не будут. Нужно взять данные Стима

**Comment by caiiiycuk** [comment]
Да, тут явно проблева в неправильной data
