### ISSUE TITLE
HD resolution and aspect ratio

### ISSUE THREAD

**Issue by stalkerg** [KranX/Vangers#58]
Малыми жертвами сделать HD разрешение.
В целом в после полноэкранного режима (F1) всё работает как надо но интерфейс и трюм - ужасно. 
Если не переделывать UI то можно попробовать отцентровать все элементы. 
Красиво полюбому не будет НО вполне играбельно и можно сделать отдельный пункт запуска в Steam (что бы не по умолчанию такие "красивости были"). 

На текущий момент я ориентируюсь на 720p выше делать уже плохо так как вылезают другие "радости". :)

**Comment by ahumellihuk** [comment]
Хотелось бы знать - ведутся ли работы над всеми этими фичами - HD разрешения, 60 FPS, другими  'next gen' тикетами? 
Я заметил, что после Июля 2014 активность в трекере почти исчезла, разработчики почти не отписываются по всем этим тикетам. 
Когда ждать крупных обновлений?

**Comment by lolmaus** [comment]
@ahumellihuk, заходи [сюда](skype:?chat&blob=SHkXVS2R-7GTFiElaYw4HcVfvLfIImQwkZTzTcF5djPAQXTX07opBJB4DpVsyXccX2x9C8wsmiaT6opFD6NOYxggHMRvbfQXVz43eTjquI0EmEtUe88neHyw5wVZS2iCuNB9Dzx7t7WUS9hXJQRojUGyuQMor0WLxK6MoBd8sCBi27PCMEATPhY27oLI5xagjKiVI7hT_1E-G88Taw8) и спроси у @stalkerg.

**Comment by lolmaus** [comment]
Секретная ссылка: skype:?chat&blob=SHkXVS2R-7GTFiElaYw4HcVfvLfIImQwkZTzTcF5djPAQXTX07opBJB4DpVsyXccX2x9C8wsmiaT6opFD6NOYxggHMRvbfQXVz43eTjquI0EmEtUe88neHyw5wVZS2iCuNB9Dzx7t7WUS9hXJQRojUGyuQMor0WLxK6MoBd8sCBi27PCMEATPhY27oLI5xagjKiVI7hT_1E-G88Taw8

**Comment by Korb** [comment]
@lolmaus, очевидно, никогда?

**Comment by fedorq** [comment]
Секретные ссылки!

On Thu, Oct 1, 2015 at 4:12 PM, Korb <notifications@github.com> wrote:

> @lolmaus <https://github.com/lolmaus>, очевидно, никогда?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KranX/Vangers/issues/58#issuecomment-144722363>.
>



-- 
--------------------------------
Best regards,
Feodor Kulikov
Levsha

Phone: +7(495) 979-44-76
Mobile: +7(916) 362-07-13
Skype: fedorq

**Comment by stalkerg** [comment]
Почему никогда? Всё зависит от людей.

**Comment by Assimilator** [comment]
В каком смысле?

**Comment by lpenguin** [comment]
@stalkerg можно закрыть?
