### ISSUE TITLE
Неправильный размер окна

### ISSUE THREAD

**Issue by XiadaOku** [KranX/Vangers#596]
При запуске собранной из мастера (c44ecd935aee) версии размер окна сильно больше чем должен быть, только после включения и выключения фуллскрина становится нормального размера

**Comment by caiiiycuk** [comment]
Что значит сильно больше? По умолчанию должна открваться на полный экран.

**Comment by XiadaOku** [comment]
![image](https://user-images.githubusercontent.com/69246170/176850043-c46c7c65-db00-42a5-aa86-6d0f3f4b474e.png)
![image](https://user-images.githubusercontent.com/69246170/176850107-529e1b4b-85b6-4575-af82-7551cc2a8e64.png)

**Comment by caiiiycuk** [comment]
Что не так?

**Comment by XiadaOku** [comment]
> Что значит сильно больше? По умолчанию должна открваться на полный экран.

ну да, практически на полный
вопрос только в том почему должна

**Comment by caiiiycuk** [comment]
там это 1 флагом меняется, можно откатить. я просто думла если ты игру запускаешь то хочешь на полный экран)

**Comment by XiadaOku** [comment]
> там это 1 флагом меняется, можно откатить. я просто думал если ты игру запускаешь то хочешь на полный экран)

для открытия на весь экран есть отдельная настройка, правда там полноценный фуллскрин
а вообще лучше сохранять размер окна (например как и все настройки при выходе)
