### ISSUE TITLE
Странная логика границ внутри окна

### ISSUE THREAD

**Issue by XiadaOku** [KranX/Vangers#602]
речь идет про черные границы у окна с неподдерживаемым соотношением сторон (левее) либо про границы в меню в hd (правее)
![image](https://user-images.githubusercontent.com/69246170/179849127-a6a3bff8-7c31-4f53-a190-9e1e24a7a5a6.png)
курсор при перемещении левее или выше границы останавливается, но правее либо ниже перемещается под границей
мелочь, но тем не менее

**Comment by caiiiycuk** [comment]
Речь про чёрный экран или курсор? Чёрный экран потому что разрешение sdl превышает возможное разрешение 2d рендеринга. Там получается аспект такой что высота становится меньше 600, это вызывает segfault. Чёрный экран может побороть, например , отрендерив фон через sdl, или сделать что бы не падал 2d рендер, но тогда нижняя граница меню будет уходить за пределы экрана. А с курсором все понятно, в соседней задаче расписал

**Comment by XiadaOku** [comment]
Речь про взаимодействие курсора с границами, то что они курсор по разному себя ведет в зависимости от места где граница, но это ладно, просто мелочь пожалуй
