### ISSUE TITLE
Вылет при победе в Ядерной Войне

### ISSUE THREAD

**Issue by ilkar399** [KranX/Vangers#61]
Происходит при сдаче 10 и более Ядробусов при наличии табутаска с задачей победы в Ядерной Войне на раффе. Судя по всему, не важно, на каком мехосе его выполнять - у меня вылетает и на ДД, и на разных раффах. Логфайл пустой. Ось - Windows 7 en x64. Могу выслать сейв перед стартом ЯВ, но не уверен, что в этом есть смысл.
В этом же табутаске вроде бы ошибка в переводе на английский - "... who can win a Nuclear War against a raffa" противоположно по смыслу правильному "... способного выиграть Ядерную Войну на раффа.

**Comment by bearoforange** [comment]
Я бы проверил, если сейв остался.

**Comment by XiadaOku** [comment]
@stalkerg можно закрывать
