### ISSUE TITLE
Баг который навсегда ломает игру

### ISSUE THREAD

**Issue by Sewer009** [KranX/Vangers#646]
Баг случился на яндексовской версии игры.

Я в игре получил артефакт механическая мессия, однако, обитатели шарахаются, когда ты завозишь его в эскейв и не пускают, поэтому я использовал абуз с сохранениями, сохранялся когда заехал и перезагружался, чтобы остаться внутри эскейва.

Меня предупреждали, что, если сделать это во время гонки, то это сломает скрипты и гонку дальше пройти невозможно, но вот то, что это полностью сломает игру...

Я проходил гонку цикс с помощью этого абуза и сначала у меня случился баг когда мой мехос перестал управляться и стал летать словно в невесомости. Прошло.

Ну, а потом я решил пройти так гонку еще раз, сохранился и теперь мои мехосы стали ездить со скоростью улитки, словно к ним камень привязали. Причем, мало того, что не помогает покупка/продажа, баг распространяется на ВСЕ мехи, так еще эта поломка перелезла на все сохранения и даже на новую игру.

Я бы с радостью передал сохранения, но я не знаю как их достать с яндексовской версии.
![Безымянный](https://github.com/user-attachments/assets/b1cd6eb3-bc84-4502-a7ad-1350cffb62a7)

**Comment by Sewer009** [comment]
Помогли исправить, баг отключает автоускорение

**Comment by stalkerg** [comment]
да, я думаю яндексовая версия имеет очень много отличий от этой.
