### ISSUE TITLE
Обновление стим версии.

### ISSUE THREAD

**Issue by ALMh** [KranX/Vangers#87]
Узнал от товарища, что Стим-версия до сих пор имеет более старую версию игры(нет многих опций), по сравнению с версией на GOG.
Было-бы неплохо обновить её.

**Comment by yvm** [comment]
В бета-версии в Steam работает сохранение ландшафта.

**Comment by nightfox696** [comment]
Может хоть скажете какой код для беты в стиме?

**Comment by eternastudento** [comment]
Планируется ли обновление steam-версии до актуальной?

**Comment by stalkerg** [comment]
Да, правда думаю после более существенных правок кода.

**Comment by Assimilator** [comment]
А можно текущую дев версию в альфу-бету запаковать или это много работы?

**Comment by stalkerg** [comment]
Вам под Windows?

**Comment by Assimilator** [comment]
Да

**Comment by AMDmi3** [comment]
@stalkerg давай всё-таки appveyor прикрутим. Если у тебя есть сборочное окружение со всеми зависимостями, можно просто его использовать.

**Comment by DiTolk** [comment]
Ура! Можно закрывать =)
